#define SEQUENCE_1 "sequence1.txt"
#define SEQUENCE_2 "sequence2.txt"
#define TEXT_ARG (string) "-text"
#define SEED_ARG (string) "-seed"
#define SCRIPT_1 (string) "-scriptfile1"
#define SCRIPT_2 (string) "-scriptfile2"
#define START_LEVEL (string) "-startlevel"
#define BONUS_ARG (string) "-bonus"